---
- name: Test DNS
  hosts: localhost
  connection: local
  become: false

  tasks:
  - name: Test 1
    debug: 
      msg: "{{ lookup('ansible.builtin.dig', 'www.redhat.com') }}"

  - name: Debug hostvars
    debug:
      var: groups
