---
- name: Test Loops
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  - name: Loop Test
    shell: "echo {{ item }}"
    loop:
      - "one"
      - "two"
      - "three"
      - "four"
      - "five"
    register: echo

  - name: Display Results
    debug:
      var: echo.results
